# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_citylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
